apiVersion: v1
kind: Pod
metadata:
  name: video-service-pod
  labels:
    app: video-service
spec:
  containers:
    - name: video-service
      image: videostreaming
      imagePullPolicy: Never
      ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: video-service-clustserip
spec:
  type: ClusterIP
  selector:
    app: video-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: video-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: video-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
